<a href="https://colab.research.google.com/github/dfmb23/Artificial-Intelligence/blob/main/Lunes01deJulio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np



a= np.array([11,22,33])
print(a.shape)
print(type(a))
print(a)

print(a[1])
print(a[:2])
print(a[1:])
a[1]= 888
print(a)

(3,)
<class 'numpy.ndarray'>
[11 22 33]
22
[11 22]
[22 33]
[ 11 888  33]


In [ ]:
import numpy as np
b=np.array(([1,2,3],[11,22,33],[111,222,333]))
print(b.shape)
print(type(b))
print(b)
print(b[1,1])
aux=b[1:,1:].copy()
print(aux.shape)
print(aux)

print('BEFORE...')
print(b)
print(aux)

aux[1,1]=1000

print('AFTER...')
print(b)
print(aux)

(3, 3)
<class 'numpy.ndarray'>
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
22
(2, 2)
[[ 22  33]
 [222 333]]
BEFORE...
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
[[ 22  33]
 [222 333]]
AFTER...
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
[[  22   33]
 [ 222 1000]]


In [ ]:
c=np.zeros((4,4))
print(c)
print(c.shape)
d=np.full((4,4),9)
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [ ]:
e=np.eye(3,3)
print(e)
f=np.ones((4,5))
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
g=np.random.random((5,5))
print(g)

[[0.75178945 0.40549183 0.40111978 0.36981267 0.71050707]
 [0.646938   0.06347887 0.89769142 0.19954837 0.42515974]
 [0.36342833 0.01714586 0.06822818 0.23167662 0.07362745]
 [0.2810133  0.3029526  0.40978384 0.02877318 0.44532059]
 [0.71481589 0.24938435 0.72477785 0.38337954 0.45672195]]


In [ ]:
tmp1=np.random.randint(1,20,(4,4))
print(tmp1)
rows=np.array([0,1,2,0])
cols=np.arange(4)
print(rows)
print(cols)
print(rows.shape)
print(cols.shape)

tmp1[rows,cols]=100
print(tmp1)

[[15  2 14 16]
 [ 7  4 11 17]
 [17 19  5  8]
 [14 19  8  2]]
[0 1 2 0]
[0 1 2 3]
(4,)
(4,)
[[100   2  14 100]
 [  7 100  11  17]
 [ 17  19 100   8]
 [ 14  19   8   2]]


In [ ]:
tmp1[rows,cols]=100
print(tmp1)

[[100   2  14 100]
 [  7 100  11  17]
 [ 17  19 100   8]
 [ 14  19   8   2]]


In [ ]:
tmp1 = np.random.randint(20, 50,(6, 6))
print(tmp1)

[[24 31 30 41 27 42]
 [48 28 41 21 43 27]
 [42 28 29 25 39 26]
 [31 40 42 26 41 44]
 [31 43 21 46 44 29]
 [44 38 44 46 38 32]]


In [ ]:
filter=(tmp1>45)
print(filter)
print(tmp1[filter])

[[False False False False False False]
 [ True False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]
 [False False False  True False False]]
[48 46 46]


In [ ]:
tmp1 = np.random.randint(1, 100,(10, 10))
print(tmp1)
par=tmp1[tmp1%2==0]
print(par)

[[42 57 89 71 90 99 94 43 82  5]
 [77 53 18 41 29  7 42 71 50 77]
 [86 61 27 71 17 16 40 36 38 77]
 [44 46 74 85 18 32 15 10 53 92]
 [97 92 96 58 77 78 67 64 23 22]
 [24 37 42 42 55 94 12 39 72  5]
 [40 31 50 93 11 97 53 80 85 81]
 [54 70 51 34 71 99 79 65  1 93]
 [22 64 91 56 94  2 98 91 21 27]
 [17 57 73 55 92 79 34 31 92 48]]
[42 90 94 82 18 42 50 86 16 40 36 38 44 46 74 18 32 10 92 92 96 58 78 64
 22 24 42 42 94 12 72 40 50 80 54 70 34 22 64 56 94  2 98 92 34 92 48]


In [ ]:
tmp3=np.array([1,2,3,4,5],dtype=np.float64)
print(tmp3.dtype)

float64


In [ ]:
x=np.array([[1,2],[11,22]])
y=np.array([[22,33],[44,55]])
print(x)
print(y)


print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))
print(np.sqrt(x))

[[ 1  2]
 [11 22]]
[[22 33]
 [44 55]]
[[23 35]
 [55 77]]
[[-21 -31]
 [-33 -33]]
[[  22   66]
 [ 484 1210]]
[[0.04545455 0.06060606]
 [0.25       0.4       ]]
[[1.         1.41421356]
 [3.31662479 4.69041576]]


In [ ]:
tmp1 = np.random.randint(1, 10,(2, 5))
print(tmp1)
aux=tmp1.mean()
print(aux)

[[9 7 5 9 2]
 [2 3 6 5 3]]
5.1


In [ ]:
print(tmp1.mean(axis=1))
print(tmp1.mean(axis=0))

[6.4 3.8]
[5.5 5.  5.5 7.  2.5]


In [10]:
import numpy as np
a=np.random.randint(1,10, (3,4))
print(a)
tmp=np.mean(a)
print(tmp)
print(a.mean())
tmp=a.mean(axis=1)
print(tmp)
tmp=(a.mean(axis=0))
print(tmp)

##para sumar todos los elementos
aux=a.sum()
print(aux)

##para calcular la mediana

medianValue=np.median(a,axis=1)
print(medianValue)


[[5 5 9 5]
 [2 2 2 5]
 [1 2 4 9]]
4.25
4.25
[6.   2.75 4.  ]
[2.66666667 3.         5.         6.33333333]
51
[5. 2. 3.]


In [12]:
##sorting (ordenar)

b=np.random.rand(10)
print(b)
print(b.shape)
b.sort()
print(b)


[0.01350676 0.28913251 0.68394949 0.90229174 0.71774838 0.43554566
 0.95474925 0.3537741  0.35059003 0.45199523]
(10,)
[0.01350676 0.28913251 0.35059003 0.3537741  0.43554566 0.45199523
 0.68394949 0.71774838 0.90229174 0.95474925]


In [13]:
##para usarvalores unicos
c=np.array([2,3,4,2,5,3,5])
print(np.unique(c))

[2 3 4 5]


In [18]:
string1=np.array(["desk", "chair", "bulb"])
string2=np.array(["lamp", "bulb", "chair"])

tmp1=np.intersect1d(string1,string2)
print(tmp1)
tmp2=np.union1d(string1,string2)
print(tmp2)

tmp3=np.setdiff1d(string1,string2)
print(tmp3)
tmp4=np.setdiff1d(string2,string1)
print(tmp4)
tmp5=np.in1d(string1,string2)
print(tmp5)

['bulb' 'chair']
['bulb' 'chair' 'desk' 'lamp']
['desk']
['lamp']
[False  True  True]


In [26]:
##broadcasting (transmitir0)

aux=np.zeros((4,3))
print(aux)
replicate=np.array([1,2,1])
aux=aux+replicate
print(aux)
replicateCol=np.array([10,10,10])
print(replicateCol.shape)
replicateCol=np.reshape(replicateCol, (3,1))
print(replicateCol.shape)
aux=np.zeros((3,3))
aux1=replicateCol+aux
print(aux1)
print("we are here ......")
vector=np.array([45])
matrixZeros=np.zeros([5,5])
print(matrixZeros)
print(matrixZeros+vector)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]]
(3,)
(3, 1)
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
we are here ......
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]]
